export const AUTH = Object.freeze({
  LOGIN: 'AUTH_LOGIN',
  LOGOUT: 'AUTH_LOGOUT',
})

export const FRIENDS = Object.freeze({
  FETCH: 'FRIENDS_FETCH',
  FETCH_HOMEPOST: 'FRIENDS_FETCH_HOMEPOST'
})

export const PROFILE = Object.freeze({
  FETCH_DETAIL: 'PROFILE_FETCH',
  FOLLOW: 'PROFILE_FOLLOW',
  UNFOLLOW: 'PROFILE_UNFOLLOW',
  FETCH_POSTS: 'PROFILE_FETCH_POSTS',
  POST_MYSTATUS: 'PROFILE_POST_MYSTATUS'
})